# Configuração do GitHub Pages
title: "Epic Games Bot Dashboard"
description: "Dashboard em tempo real para monitorar jogos gratuitos da Epic Games"
author: "Seu Nome"
baseurl: ""
url: "https://SEU_USUARIO.github.io"

# Tema
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Configurações de build
markdown: kramdown
highlighter: rouge

# Configurações de SEO
lang: pt-BR
locale: pt_BR

# Excluir arquivos do build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
